name: Angular CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build -- --configuration=production

      - name: Deploy to GitHub Pages
        uses: JamesIArmes/github-pages-deploy-action@3.8.0
        with:
          branch: gh-pages
          folder: dist/Portfolio
          token: ${{ secrets.GITHUB_TOKEN }} # GitHub automatically creates this secret
